name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job has ben triggered 🤓"
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} has been cloned by the runner "
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
      - name: Build and Test
      - run: echo"The workflow is now ready to ru your test"
      - run: sbt -v +tests