name: Scala CI

on:
  push:
    branches: [ path ]
  pull_request:
    branches: [ path ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run:  echo "About to checkout out 😀"
    - uses: actions/checkout@v2
    - run:  echo "The repository ${{github.repository}} is being cloned by the runner"
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run tests
      run: sbt test
